*METAKUNA*
<h1 style="text-align:center;">Proyecto final </h1>
<h1 style="text-align:center;"> LIMPIEZA DATA SAGA PARTE 2 </h1>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/datasaga1.2.csv',sep=';')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1518 entries, 0 to 1517
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   bat          291 non-null    object 
 1   brand        1517 non-null   object 
 2   cam_front    1231 non-null   object 
 3   cam_main     1102 non-null   float64
 4   condition    1518 non-null   object 
 5   conect       1518 non-null   object 
 6   cores        358 non-null    float64
 7   cpu_vel      322 non-null    float64
 8   mem_int      1466 non-null   object 
 9   mem_ram      1394 non-null   object 
 10  model        1365 non-null   object 
 11  os           1360 non-null   object 
 12  product      1518 non-null   object 
 13  modelo       1518 non-null   object 
 14  screen_size  998 non-null    float64
 15  screen_type  416 non-null    object 
 16  warranty     1518 non-null   int64  
 17  water_res    377 non-null    object 
 18  price_norm   1516 non-null   object 
 19  price_

In [ ]:
## convirtiendo las varaibles nominales a minusculas, para estandirizar con las demas datas.

df['brand'] = df['brand'].str.lower()
#df['color'] = df['color'].str.lower()
df['condition'] = df['condition'].str.lower()
df['contect'] = df['conect'].str.lower()
#df['cores'] = df['cores'].str.lower()
df['model'] = df['model'].str.lower()
df['os'] = df['os'].str.lower()
df['modelo'] = df['modelo'].str.lower()
df['screen_type'] = df['screen_type'].str.lower()
df['water_res'] = df['water_res'].str.lower()

In [ ]:
df['cpu_vel'].unique()

array([   nan,   2.4 ,   3.36,   2.9 ,   2.3 ,   2.  ,   2.8 ,   2.99,
         3.19,   2.65,   1.6 ,   2.5 ,   3.23,   1.8 ,   2.84, 239.  ,
         3.  ,   2.39,   3.18,   2.2 ,   1.3 ,   2.7 ,   2.35,   1.5 ,
         2.6 ,   1.  ,   2.1 ,   1.2 ,   3.46,   2.96,   2.05,   2.73])

In [ ]:
df.head()

bat    brand cam_front  cam_main condition conect  cores  cpu_vel mem_int  \
0   NaN   xiaomi         5       8.0     nuevo     4G    NaN      NaN      32   
1  5000  samsung        13      48.0     nuevo     5G    8.0     2.40     128   
2  3900  samsung        12      50.0     nuevo     5G    8.0     3.36     128   
3          apple        12       NaN     nuevo     5G    6.0      NaN     128   
4  4300    honor        16      64.0     nuevo     4G    NaN      NaN     128   

  mem_ram  ...          os                                            product  \
0       2  ...     android  Smartphone 6.5 2GB RAM 32GB ROM Redmi A1 - Lig...   
1       6  ...     android                     Galaxy A33 5G 128GB 6GB Negro    
2       8  ...  android 13                              Galaxy S23 128GB 8GB    
3          ...         ios                         Apple iPhone 14 Pro 128GB    
4       6  ...  android 11  Smartphone Honor 50 Lite 128Gb 6Gb Nano Sim Si...   

          modelo screen_size        screen_type warranty  water_res  \
0       redmi a1         6.0                NaN        3        NaN   
1     galaxy a33         6.4       super amoled        3        NaN   
2     galaxy s23         6.1  dynamic amoled 2x        3         si   
3  iphone 14 pro         6.1   super retina xdr        3         si   
4  honor 50 lite         NaN                NaN        3         no   

  price_norm price_off  contect  
0                699.0       4g  
1       1199       NaN       5g  
2               3999.0       5g  
3       5899       NaN       5g  
4        999       NaN       4g  

[5 rows x 21 columns]

In [ ]:
# obteniendo de la columna producto la palabra 5G, si es que tiene
df['conect'] = np.where(df['product'].str.contains('5G'), '5G', df['conect'])

In [ ]:
df["conect"]=df['conect'].astype(str)

In [ ]:
df['conect'].unique()

array(['4G', '5G', '3G', '2G'], dtype=object)

In [ ]:
# volviendo a mayusculas esos valores y reemplazando los nan por 4G
df['conect'] = df['conect'].replace(['nan', '4G '], '4G')
df['conect'] = df['conect'].replace(['4g'], '4G')
df['conect'] = df['conect'].replace(['5g'], '5G')

In [ ]:
df['condition'].unique()

array(['nuevo', 'reacondicionado'], dtype=object)

In [ ]:
# agrupando las eriquetas similares en una sola categoria
df['condition'] = df['condition'].replace(['reacondicionado ', 'reacondicionado', 'reacondicionado excelente (a)', 'reacondicionado detalle estético (b)', 'sin uso con detalle estético'], 'reacondicionado')
df['condition'].fillna(value='nuevo', inplace=True)

In [ ]:
df['condition'].unique()

array(['nuevo', 'reacondicionado'], dtype=object)

In [ ]:
df['warranty'] = np.where(df['condition'] == 'nuevo', 12, 3)

In [ ]:
# haciendo lo mismo para water_res agrupar y reemplazar
var = [
        'ip68 (protegido contra inmersión)',
        'ip68',
        'ipx0 (sin protección especial)', 
        'ipx8 (protegido contra inmersión)',
        'ipx7 (protegido contra los efectos de la inmersión a 1 metro durante 30 minutos)',
        'ipx1 (protegido contra el agua vertida: goteo)',
        'ipx4 (protegido contra las salpicaduras de agua)',
        'ipx6 (protegido contra chorros a alta presión)',
        'ipx5 (protegido contra el agua en chorros a presión)',
        'ipx3 (protegido contra el agua rociada: spray)', 'sí',
        'ipx8 (protegido contra inmersión: la profundidad debe ser indicada por el proveedor en información adicional)',
        'ipx2 (protegido contra el agua vertida: goteo, cuando está inclinado hasta 15 grados con respecto a su posición normal)'
       ]
df['water_res'] = df['water_res'].replace(var, 'si')

In [ ]:
df['water_res'].unique()

array([nan, 'si', 'no'], dtype=object)

In [ ]:
df['modelo'] = df['modelo'].str.strip()

In [ ]:
df['cores'].unique()

array([nan,  8.,  6.,  4.,  2.,  1.,  3.])

In [ ]:
# reemplazando los valores de la columna cores por valores numericos
df['cores'] = df['cores'].replace(['octa core'], '8')
df['cores'] = df['cores'].replace(['hexa core'], '6')
df['cores'] = df['cores'].replace(['dual core'], '2')
df['cores'] = df['cores'].replace(['quad core'], '4')
df['cores'] = df['cores'].replace(['triple core'], '3')
df['cores'] = df['cores'].replace(['single core'], '1')

In [ ]:
df['cores'].unique()

array([nan,  8.,  6.,  4.,  2.,  1.,  3.])

In [ ]:
#obteniendo a partir de la columna porduct valores para la columna mem_int 
df['mem_int'] = np.where(df['product'].str.contains('128'), 128, df['mem_int'])
df['mem_int'] = np.where(df['product'].str.contains('256'), 256, df['mem_int'])
df['mem_int'] = np.where(df['product'].str.contains('64'), 64, df['mem_int'])
df['mem_int'] = np.where(df['product'].str.contains('512'), 512, df['mem_int'])
df['mem_int'] = np.where(df['product'].str.contains('32'), 32, df['mem_int'])

In [ ]:
df['os'].unique()

array(['android', 'android 13', 'ios', 'android 11', 'android 12', nan,
       'android tv', 'android 10', 'android 11 go', 'android 8.1',
       'android¿ 11', 'de fabricante', 'android 7', 'emui 12',
       'windows 7', 'android 9.0', 'andriod', 'sin os', 'no aplica',
       'android 8', 'linux', 'universal', 'nokia series os', 'osx',
       'kaios', 'ipados', 'spreadtrum'], dtype=object)

In [ ]:
#agrupando valores similares en algunas categorias, en la variable os
dta = ['android 13', 'android 11', 'android 12','android tv', 
       'android 10', 'android 11 go', 'android 8.1',
       'android¿ 11', 'android 7', 'emui 12','android 8','andriod','android 9.0']
col = [
    'de fabricante', 'windows 7',
       'sin os', 'no aplica', 'linux', 'universal', 'nokia series os',
       'osx', 'kaios', 'ipados', 'spreadtrum'
      ]
df['os'] = df['os'].replace(dta, 'android')
df['os'] = df['os'].replace(col, 'otros')

In [ ]:
df['os'].unique()

array(['android', 'ios', nan, 'otros'], dtype=object)

In [ ]:
# exportando el dataframe trabajado a un archivo csv
df.to_csv('datasaga1.3.csv', index=False)